name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'LICENSE'
      - '**.md'
  pull_request:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      test_release:
        description: 'Test release?'
        required: true
        default: 'false'
      rebuild_sysroot:
        description: 'Force rebuild sysroot?'
        required: true
        default: 'false'

env:
  BUILD_XCODE_PATH: /Applications/Xcode_16.2.app
  RUNNER_IMAGE: macos-14

jobs:
  configuration:
    name: Setup configuration
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.checker.outputs.runners }}
      github-runner: ${{ steps.checker.outputs.github-runner }}
    steps:
    - name: Check for hosted runners
      id: checker
      shell: bash
      env:
        IS_SELF_HOSTED_RUNNER: ${{ vars.IS_SELF_HOSTED_RUNNER || (github.repository_owner == 'utmapp' && 'true') }}
      run: |
        echo "github-runner='$RUNNER_IMAGE'" >> $GITHUB_OUTPUT
        if [ "$IS_SELF_HOSTED_RUNNER" == "true" ]; then
          echo "runners=['self-hosted', 'macOS']" >> $GITHUB_OUTPUT
        else
          echo "runners='$RUNNER_IMAGE'" >> $GITHUB_OUTPUT
        fi
  build-sysroot:
    name: Build Sysroot
    runs-on: ${{ fromJSON(needs.configuration.outputs.runner) }}
    needs: configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup Xcode
        shell: bash
        run: |
          [[ "$(xcode-select -p)" == "${{ env.BUILD_XCODE_PATH }}"* ]] || sudo xcode-select -s "${{ env.BUILD_XCODE_PATH }}"
      - name: Cache Sysroot
        id: cache-sysroot
        uses: osy/actions-cache@v3
        with:
          path: sysroot-macos-arm64
          key: macos-arm64-${{ hashFiles('scripts/build_dependencies.sh') }}-${{ hashFiles('patches/**') }}
          upload-chunk-size: 1048576 # 1 MiB
      - name: Setup Path
        shell: bash
        run: |
          echo "/usr/local/opt/bison/bin:/opt/homebrew/opt/bison/bin" >> $GITHUB_PATH
      - name: Install Requirements
        run: |
          brew uninstall cmake
          brew install bison pkg-config gettext glib-utils libgpg-error nasm make meson
          pip3 install --user six pyparsing --break-system-packages
          rm -f /usr/local/lib/pkgconfig/*.pc
      - name: Build Sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true' || github.event.inputs.rebuild_sysroot == 'true'
        run: ./scripts/build_dependencies.sh -p macos -a arm64
      - name: Compress Sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true' || github.event_name == 'release' || github.event.inputs.test_release == 'true'
        run: tar -acf sysroot.tgz sysroot*
      - name: Upload Sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true' || github.event_name == 'release' || github.event.inputs.test_release == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Sysroot-macos-arm64
          path: sysroot.tgz
  build-utm:
    name: Build UTM
    runs-on: ${{ fromJSON(needs.configuration.outputs.runner) }}
    needs: [configuration, build-sysroot]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache Sysroot
        id: cache-sysroot
        uses: osy/actions-cache@v3
        with:
          path: sysroot-macos-arm64
          key: macos-arm64-${{ hashFiles('scripts/build_dependencies.sh') }}-${{ hashFiles('patches/**') }}
      - name: Check Cache
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        uses: actions/github-script@v6
        with:
          script: core.setFailed('Cached sysroot not found!')
      - name: Setup Xcode
        shell: bash
        run: |
          [[ "$(xcode-select -p)" == "${{ env.BUILD_XCODE_PATH }}"* ]] || sudo xcode-select -s "${{ env.BUILD_XCODE_PATH }}"
      - name: Build UTM
        run: |
          ./scripts/build_utm.sh -k macosx -s macOS -a arm64 -o UTM
          tar -acf UTM.xcarchive.tgz UTM.xcarchive
      - name: Upload UTM
        uses: actions/upload-artifact@v4
        with:
          name: UTM-macos-arm64
          path: UTM.xcarchive.tgz
  package-mac:
    name: Package (macOS)
    runs-on: ${{ fromJSON(needs.configuration.outputs.github-runner) }}
    needs: [configuration, build-utm]
    if: github.event_name == 'release' || github.event.inputs.test_release == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Xcode
        shell: bash
        run: |
          [[ "$(xcode-select -p)" == "${{ env.BUILD_XCODE_PATH }}"* ]] || sudo xcode-select -s "${{ env.BUILD_XCODE_PATH }}"
      - name: Import signing certificate into keychain
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
      - name: Import App Store Connect API Key
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo $AUTHKEY_API_KEY | base64 --decode -o ~/.appstoreconnect/private_keys/AuthKey_$API_KEY.p8
        env:
          AUTHKEY_API_KEY: ${{ secrets.CONNECT_KEY }}
          API_KEY: ${{ vars.CONNECT_KEY_ID }}
      - name: Install Provisioning Profiles
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo $PROFILE_DATA | base64 --decode -o ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.provisionprofile
          echo $HELPER_PROFILE_DATA | base64 --decode -o ~/Library/MobileDevice/Provisioning\ Profiles/$HELPER_PROFILE_UUID.provisionprofile
          echo $LAUNCHER_PROFILE_DATA | base64 --decode -o ~/Library/MobileDevice/Provisioning\ Profiles/$LAUNCHER_PROFILE_UUID.provisionprofile
        env:
          PROFILE_DATA: ${{ vars.PROFILE_DATA }}
          PROFILE_UUID: ${{ vars.PROFILE_UUID }}
          HELPER_PROFILE_DATA: ${{ vars.HELPER_PROFILE_DATA }}
          HELPER_PROFILE_UUID: ${{ vars.HELPER_PROFILE_UUID }}
          LAUNCHER_PROFILE_DATA: ${{ vars.LAUNCHER_PROFILE_DATA }}
          LAUNCHER_PROFILE_UUID: ${{ vars.LAUNCHER_PROFILE_UUID }}
      - name: Install appdmg
        run: npm install -g appdmg
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: UTM-macos-arm64
      - name: Package for Release
        run: |
          tar -xf UTM.xcarchive.tgz
          ./scripts/package_mac.sh developer-id UTM.xcarchive . "$SIGNING_TEAM_ID" "$PROFILE_UUID" "$HELPER_PROFILE_UUID" "$LAUNCHER_PROFILE_UUID"
        env:
          SIGNING_TEAM_ID: ${{ vars.SIGNING_TEAM_ID }}
          PROFILE_UUID: ${{ vars.PROFILE_UUID }}
          HELPER_PROFILE_UUID: ${{ vars.HELPER_PROFILE_UUID }}
          LAUNCHER_PROFILE_UUID: ${{ vars.LAUNCHER_PROFILE_UUID }}
      - name: Notarize app
        run: |
          xcrun notarytool submit --issuer "$ISSUER_UUID" --key-id "$API_KEY" --key "~/.appstoreconnect/private_keys/AuthKey_$API_KEY.p8" --team-id "$SIGNING_TEAM_ID" --wait "UTM.dmg"
          xcrun stapler staple "UTM.dmg"
        env:
          SIGNING_TEAM_ID: ${{ vars.SIGNING_TEAM_ID }}
          ISSUER_UUID: ${{ vars.CONNECT_ISSUER_ID }}
          API_KEY: ${{ vars.CONNECT_KEY_ID }}
      - name: Upload Artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: UTM-dmg
          path: UTM.dmg
      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: UTM.dmg
          asset_name: UTM.dmg
          asset_content_type: application/octet-stream
  submit-mac:
    name: Submit (macOS)
    runs-on: ${{ fromJSON(needs.configuration.outputs.github-runner) }}
    needs: [configuration, build-utm]
    if: github.event_name == 'release' || github.event.inputs.test_release == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Xcode
        shell: bash
        run: |
          [[ "$(xcode-select -p)" == "${{ env.BUILD_XCODE_PATH }}"* ]] || sudo xcode-select -s "${{ env.BUILD_XCODE_PATH }}"
      - name: Import signing certificate into keychain
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
      - name: Import App Store Connect API Key
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo $AUTHKEY_API_KEY | base64 --decode -o ~/.appstoreconnect/private_keys/AuthKey_$API_KEY.p8
        env:
          AUTHKEY_API_KEY: ${{ secrets.CONNECT_KEY }}
          API_KEY: ${{ vars.CONNECT_KEY_ID }}
      - name: Install Provisioning Profiles
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo $PROFILE_DATA | base64 --decode -o ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.provisionprofile
          echo $HELPER_PROFILE_DATA | base64 --decode -o ~/Library/MobileDevice/Provisioning\ Profiles/$HELPER_PROFILE_UUID.provisionprofile
          echo $LAUNCHER_PROFILE_DATA | base64 --decode -o ~/Library/MobileDevice/Provisioning\ Profiles/$LAUNCHER_PROFILE_UUID.provisionprofile
        env:
          PROFILE_DATA: ${{ vars.APP_STORE_PROFILE_DATA }}
          PROFILE_UUID: ${{ vars.APP_STORE_PROFILE_UUID }}
          HELPER_PROFILE_DATA: ${{ vars.APP_STORE_HELPER_PROFILE_DATA }}
          HELPER_PROFILE_UUID: ${{ vars.APP_STORE_HELPER_PROFILE_UUID }}
          LAUNCHER_PROFILE_DATA: ${{ vars.APP_STORE_LAUNCHER_PROFILE_DATA }}
          LAUNCHER_PROFILE_UUID: ${{ vars.APP_STORE_LAUNCHER_PROFILE_UUID }}
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: UTM-macos-arm64
      - name: Package for App Store
        run: |
          tar -xf UTM.xcarchive.tgz
          ./scripts/package_mac.sh app-store UTM.xcarchive . "$SIGNING_TEAM_ID" "$PROFILE_UUID" "$HELPER_PROFILE_UUID" "$LAUNCHER_PROFILE_UUID"
        env:
          SIGNING_TEAM_ID: ${{ vars.SIGNING_TEAM_ID }}
          PROFILE_UUID: ${{ vars.APP_STORE_PROFILE_UUID }}
          HELPER_PROFILE_UUID: ${{ vars.APP_STORE_HELPER_PROFILE_UUID }}
          LAUNCHER_PROFILE_UUID: ${{ vars.APP_STORE_LAUNCHER_PROFILE_UUID }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UTM-pkg
          path: UTM.pkg
      - name: Upload app to App Store Connect
        if: github.event_name == 'release'
        run: |
          xcrun altool --upload-app -t macos -f "UTM.pkg" --apiKey "$API_KEY" --apiIssuer "$ISSUER_UUID"
        env:
          ISSUER_UUID: ${{ vars.CONNECT_ISSUER_ID }}
          API_KEY: ${{ vars.CONNECT_KEY_ID }}
